### ISSUE TITLE
build-tools-24 is missing from repository

### ISSUE THREAD

**Issue by kylannjohnson** [tadfisher/android-sdk-updater#27]
I tried to execute:  `android-sdk-updater build-tools` but got the following error

```
Remote repository is missing package 'build-tools'
Remote repository is missing package 'build-tools-24.0.0-preview'
```

However, `android update sdk --no-ui --filter build-tools-24.0.0` successfully downloaded build-tools 24.  

Could those repos not be included in this project?

**Comment by JakeWharton** [comment]
`build-tools` is not an artifact name. Use `build-tools-24.0.0` which works fine.

**Comment by kylannjohnson** [comment]
@JakeWharton Agreed.  I was slightly confused at the result.  Does the tool attempt to resolve the artifact?  I put in 'build-tool-24' but it searched for build-tools-24.0.0-preview

**Comment by JakeWharton** [comment]
Ideally the script would fail if you give it an invalid artifact ID like that. You can find a list of valid ones by running `android list sdk -a -u -e | grep 'id:'`

**Comment by tadfisher** [comment]
It's difficult to resolve package versions because they are inconsistent
across packages and are included in the package name. @jw's suggestion
makes sense.

**Comment by kylannjohnson** [comment]
I agree that attempting to resolve a bogus artifact is too brittle of a solution.  I wanted to ask one last question before closing this issue.  On one of my machines I had `build-tools-24.0.0-preview`.  I ran `android-sdk-updater build-tools-24.0.0`, but got:  

```
Scanning .android-sdk for installed packages...
    31 packages installed.
Querying update sites for available packages...
    153 packages available.
Remote repository is missing package 'build-tools-24.0.0-preview'
```

Is there a way to resolve the issue other than deleting the `build-tools-24.0.0-preview` folder manually?  (it seems that in this case, one could also remove '-preview')

**Comment by tadfisher** [comment]
That would require preview repository support in the `android sdk` tool, or for some additional name-mangling on our end to detect preview packages. I'm not sure the last option is the *right* thing to do, but given that this project is a giant kludge, I can see how it'd be useful.

**Comment by kylannjohnson** [comment]
There could be a simpler solution.  Presently, the script stops if it encounters a build-artifact locally that is not found in the remote repo.  Perhaps it could report that to the user as a warning and continue processing.  So, when `build-tools-24.0.0-preview` drops the `-preview`, the right artifact name would work.  What do you think?

**Comment by tadfisher** [comment]
The current behavior was requested in #21. I think it makes sense for installing new packages, but perhaps it should be tweaked to distinguish between the update and new-install cases.

**Comment by kylannjohnson** [comment]
I tend to agree.  If the user enters `bogus-artifact`, then an error should be thrown.  But if an existing artifact is no longer there, a warning is given instead.
